### ISSUE TITLE
Make the font embeddable using an @font-face CSS rule

### ISSUE THREAD

**Issue by eddieantonio** [Algonquian-Dictionaries-Project/CreeSyllabicsFonts#1]
This should emulate how Google Fonts works. The README gives you some HTML/CSS to copy-paste, and you put it in your website, and then _boom_! You have syllabics fonts on your website! I'm not 100% sure [the license](https://github.com/Algonquian-Dictionaries-Project/CreeSyllabicsFonts/blob/main/BJCreeUni/LICENCE) allows this, though.

1. Turn on [GitHub pages hosting from the default branch](https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site)
2. Make a `.css` file that contains the `@font-face` rule. Something similar to:

```css
@font-face {
  font-family: "BJCree UNI";
  font-display: swap;
  src: url("/BJCreeUni/BJCreeUni.woff2") format("woff2"),
       url("/BJCreeUni/BJCreeUni.woff") format("woff");
}
```

3. Add a copy-pastable snippet in the README! Again, something like:

> To embed this font, copy-paste this snippet into the `<head>` of your HTML:
>
>  ```html
>  <link href="https://Algonquian-Dictionaries-Project.github.io/CreeSyllabicsFonts/BJCreeUNI.css"  rel="stylesheet" >
>  ```
>
> CSS rules to use this font family:
>
> ```css
>  font-family: "BJCree UNI", serif;
> ```

And when this is done, I'll blog about it and tell the world that this is a [recommended way to display syllabics on their websites](https://blog.mothertongues.org/tutorial-syllabics-fonts/)! 😄 

If this sounds doable (both technically and legally), I can open a PR for steps 2 and 3. I **cannot** do step 1 — a repository administrator must do that.
